---
- hosts: all
  remote_user: administrator
  tasks:
   - name: Run the equivalent of "apt-get update" as a separate step
     become: yes
     become_method: sudo
     yum:     
      name: httpd
      state: present
